### ISSUE TITLE
Add the link of Codepen implementation of the module in README.md

### ISSUE THREAD

**Issue by plxity** [Awesome-React-Modules/React-Pincode#7] opened 2020-02-17 19:23 UTC

**Comment by samidhaVerma** [comment] 2020-02-19 19:45
Hey, I think I will take this up: any specific requirements in the implementation?

**Comment by plxity** [comment] 2020-02-20 08:00
@samidhaVerma No specific requirements. Just a simple flow would do.

**Comment by siddhishree** [comment] 2020-03-03 11:17
Hey, Can I work on this issue?

**Comment by plxity** [comment] 2020-03-03 11:26
@siddhishree Yes, sure.

**Comment by plxity** [comment] 2020-03-06 18:09
@siddhishree What is the progress?

**Comment by siddhishree** [comment] 2020-03-06 18:10
Working on it. Would be done by tonight.

**Comment by siddhishree** [comment] 2020-03-06 19:08
@plxity I am done with my side of the work but issue #26 hasn't been merged yet which might lead to inconsistencies. So should I make my PR or wait for issue #26?

**Comment by plxity** [comment] 2020-03-07 10:14
@siddhishree Wait for the issue #26 to get merged.

**Comment by siddhishree** [comment] 2020-03-07 10:47
@plxity Issue #26 has been merged. So I think my PR is good to go.

**Comment by siddhishree** [comment] 2020-03-11 06:45
@plxity The issue is not labeled as anyone of beginner, easy, medium or hard and hence my score hasn't been updated. Can you please add a suitable label?

**Comment by plxity** [comment] 2020-03-11 09:23
@siddhishree Yes sure.

**Closed** 2020-03-12 22:24 UTC
Labels: documentation, easy, good first issue, gssoc20
